export type BibleBook = {
  id: string;
  abbreviation: string;
  name: string;
  chapters: number;
};

export const CATHOLIC_BIBLE_BOOKS: BibleBook[] = [
  { id: 'GEN', abbreviation: 'Gn', name: 'Genesis', chapters: 50 },
  { id: 'EXO', abbreviation: 'Ex', name: 'Exodo', chapters: 40 },
  { id: 'LEV', abbreviation: 'Lv', name: 'Levitico', chapters: 27 },
  { id: 'NUM', abbreviation: 'Nm', name: 'Numeros', chapters: 36 },
  { id: 'DEU', abbreviation: 'Dt', name: 'Deuteronomio', chapters: 34 },
  { id: 'JOS', abbreviation: 'Js', name: 'Josue', chapters: 24 },
  { id: 'JDG', abbreviation: 'Jz', name: 'Juizes', chapters: 21 },
  { id: 'RUT', abbreviation: 'Rt', name: 'Rute', chapters: 4 },
  { id: '1SA', abbreviation: '1Sm', name: '1 Samuel', chapters: 31 },
  { id: '2SA', abbreviation: '2Sm', name: '2 Samuel', chapters: 24 },
  { id: '1KI', abbreviation: '1Rs', name: '1 Reis', chapters: 22 },
  { id: '2KI', abbreviation: '2Rs', name: '2 Reis', chapters: 25 },
  { id: '1CH', abbreviation: '1Cr', name: '1 Cronicas', chapters: 29 },
  { id: '2CH', abbreviation: '2Cr', name: '2 Cronicas', chapters: 36 },
  { id: 'EZR', abbreviation: 'Esd', name: 'Esdras', chapters: 10 },
  { id: 'NEH', abbreviation: 'Ne', name: 'Neemias', chapters: 13 },
  { id: 'TOB', abbreviation: 'Tb', name: 'Tobias', chapters: 14 },
  { id: 'JDT', abbreviation: 'Jt', name: 'Judite', chapters: 16 },
  { id: 'EST', abbreviation: 'Est', name: 'Ester', chapters: 16 },
  { id: '1MA', abbreviation: '1Mc', name: '1 Macabeus', chapters: 16 },
  { id: '2MA', abbreviation: '2Mc', name: '2 Macabeus', chapters: 15 },
  { id: 'JOB', abbreviation: 'Jo', name: 'Job', chapters: 42 },
  { id: 'PSA', abbreviation: 'Sl', name: 'Salmos', chapters: 150 },
  { id: 'PRO', abbreviation: 'Pr', name: 'Proverbios', chapters: 31 },
  { id: 'ECC', abbreviation: 'Ecl', name: 'Eclesiastes', chapters: 12 },
  { id: 'SNG', abbreviation: 'Ct', name: 'Cantico dos Canticos', chapters: 8 },
  { id: 'WIS', abbreviation: 'Sb', name: 'Sabedoria', chapters: 19 },
  { id: 'SIR', abbreviation: 'Eclo', name: 'Eclesiastico', chapters: 51 },
  { id: 'ISA', abbreviation: 'Is', name: 'Isaias', chapters: 66 },
  { id: 'JER', abbreviation: 'Jr', name: 'Jeremias', chapters: 52 },
  { id: 'LAM', abbreviation: 'Lm', name: 'Lamentacoes', chapters: 5 },
  { id: 'BAR', abbreviation: 'Br', name: 'Baruc', chapters: 6 },
  { id: 'EZK', abbreviation: 'Ez', name: 'Ezequiel', chapters: 48 },
  { id: 'DAN', abbreviation: 'Dn', name: 'Daniel', chapters: 14 },
  { id: 'HOS', abbreviation: 'Os', name: 'Oseias', chapters: 14 },
  { id: 'JOL', abbreviation: 'Jl', name: 'Joel', chapters: 4 },
  { id: 'AMO', abbreviation: 'Am', name: 'Amos', chapters: 9 },
  { id: 'OBA', abbreviation: 'Abd', name: 'Abdias', chapters: 1 },
  { id: 'JON', abbreviation: 'Jn', name: 'Jonas', chapters: 4 },
  { id: 'MIC', abbreviation: 'Mq', name: 'Miqueias', chapters: 7 },
  { id: 'NAM', abbreviation: 'Na', name: 'Naum', chapters: 3 },
  { id: 'HAB', abbreviation: 'Hab', name: 'Habacuc', chapters: 3 },
  { id: 'ZEP', abbreviation: 'Sf', name: 'Sofonias', chapters: 3 },
  { id: 'HAG', abbreviation: 'Ag', name: 'Ageu', chapters: 2 },
  { id: 'ZEC', abbreviation: 'Zc', name: 'Zacarias', chapters: 14 },
  { id: 'MAL', abbreviation: 'Ml', name: 'Malaquias', chapters: 3 },
  { id: 'MAT', abbreviation: 'Mt', name: 'Mateus', chapters: 28 },
  { id: 'MRK', abbreviation: 'Mc', name: 'Marcos', chapters: 16 },
  { id: 'LUK', abbreviation: 'Lc', name: 'Lucas', chapters: 24 },
  { id: 'JHN', abbreviation: 'Jo', name: 'Joao', chapters: 21 },
  { id: 'ACT', abbreviation: 'At', name: 'Atos', chapters: 28 },
  { id: 'ROM', abbreviation: 'Rm', name: 'Romanos', chapters: 16 },
  { id: '1CO', abbreviation: '1Cor', name: '1 Corintios', chapters: 16 },
  { id: '2CO', abbreviation: '2Cor', name: '2 Corintios', chapters: 13 },
  { id: 'GAL', abbreviation: 'Gl', name: 'Galatas', chapters: 6 },
  { id: 'EPH', abbreviation: 'Ef', name: 'Efesios', chapters: 6 },
  { id: 'PHP', abbreviation: 'Fl', name: 'Filipenses', chapters: 4 },
  { id: 'COL', abbreviation: 'Cl', name: 'Colossenses', chapters: 4 },
  { id: '1TH', abbreviation: '1Ts', name: '1 Tessalonicenses', chapters: 5 },
  { id: '2TH', abbreviation: '2Ts', name: '2 Tessalonicenses', chapters: 3 },
  { id: '1TI', abbreviation: '1Tm', name: '1 Timoteo', chapters: 6 },
  { id: '2TI', abbreviation: '2Tm', name: '2 Timoteo', chapters: 4 },
  { id: 'TIT', abbreviation: 'Tt', name: 'Tito', chapters: 3 },
  { id: 'PHM', abbreviation: 'Fm', name: 'Filemom', chapters: 1 },
  { id: 'HEB', abbreviation: 'Hb', name: 'Hebreus', chapters: 13 },
  { id: 'JAS', abbreviation: 'Tg', name: 'Tiago', chapters: 5 },
  { id: '1PE', abbreviation: '1Pd', name: '1 Pedro', chapters: 5 },
  { id: '2PE', abbreviation: '2Pd', name: '2 Pedro', chapters: 3 },
  { id: '1JN', abbreviation: '1Jo', name: '1 Joao', chapters: 5 },
  { id: '2JN', abbreviation: '2Jo', name: '2 Joao', chapters: 1 },
  { id: '3JN', abbreviation: '3Jo', name: '3 Joao', chapters: 1 },
  { id: 'JUD', abbreviation: 'Jd', name: 'Judas', chapters: 1 },
  { id: 'REV', abbreviation: 'Ap', name: 'Apocalipse', chapters: 22 },
];

export const TOTAL_BIBLE_CHAPTERS = CATHOLIC_BIBLE_BOOKS.reduce(
  (total, book) => total + book.chapters,
  0,
);
